# frozen_string_literal: true
#
# Full-lifecycle e2e: triage → code → test → demo-review.
#
# All assertions read the rendered DOM. No /api/* calls. The only HTTP this
# test makes is via gh (fixture create/teardown) and the browser. See
# AGENTS.md for the rules.

require 'minitest/autorun'
require_relative 'helper'

class TestE2ELifecycle < Minitest::Test
  REQUIRED_ENV = %w[SYNTHUP_TENANT SYNTHUP_API_KEY E2E_GITHUB_REPO].freeze

  # Max wall-clock runtime per task (Synthup latency varies a lot).
  # The full sequence (router.rb): triage → code → test → demo-review
  # → wait-approval. The interactive gate fires before every routed action
  # except the very first triage dispatch (run.rb:151-158).
  #
  # When waiting for the gate of task N, the prior task is in flight — so the
  # gate-wait budget is RUN_BUDGETS[prior_task]. See `walk_lifecycle` below.
  RUN_BUDGETS = {
    'issue-triage.md' => 5 * 60,
    'code.md'         => 15 * 60,
    'test.md'         => 5 * 60,
    'demo-review.md'  => 3 * 60
  }.freeze
  WAIT_APPROVAL_BUDGET = 60

  def setup
    missing = REQUIRED_ENV.select { |k| ENV[k].to_s.strip.empty? }
    skip "missing env: #{missing.join(', ')} (set in tests/.env)" unless missing.empty?

    @repo     = ENV.fetch('E2E_GITHUB_REPO')
    @headless = ENV['E2E_HEADLESS'] != '0'

    # Don't pass through SYNTHUP_TENANT / SYNTHUP_API_KEY to the orchestrator —
    # those env values would short-circuit the UI config flow we want to test.
    # The orchestrator's data dir is isolated, so saving creds via the UI is safe.
    @orch = E2E::OrchestratorProcess.new(env: {
      'SYNTHUP_TENANT'  => nil,
      'SYNTHUP_API_KEY' => nil
    }).start

    @issue = E2E::Gh.create_issue(
      repo:  @repo,
      title: '[e2e] add tmp/e2e/ to .gitignore',
      body:  "Automated e2e test fixture. Add `tmp/e2e/` to `.gitignore`.\n\n" \
             'Generated by `bundle exec ruby tests/e2e/run.rb`. Safe to close.'
    )

    @browser = E2E::Browser.new(headless: @headless)
  end

  def teardown
    @browser&.quit
    @orch&.stop

    if @pr_number
      E2E::Gh.close_pr(repo: @repo, number: @pr_number, delete_branch: true)
    end
    if @issue
      E2E::Gh.close_issue(repo: @repo, number: @issue[:number])
    end

    # Dump the orchestrator log BEFORE cleanup. On failure, also keep the data
    # dir around so the dev can inspect everything (state files, raw logs).
    if @orch
      if passed?
        @orch.cleanup
      else
        warn "\n[e2e] orchestrator log: #{@orch.log_path}"
        warn @orch.tail_log(lines: 80)
        warn "[e2e] data dir kept for inspection: #{@orch.data_dir}"
      end
    end
  end

  def test_full_lifecycle_to_demo_review
    @browser.goto(@orch.url)

    configure_synthup
    add_project

    wait_for_triage
    # Gate-wait budget == prior task's run budget, since the gate appears once
    # the prior task finishes and the router routes its report.
    walk_interactive_gate('code.md',        RUN_BUDGETS['issue-triage.md'])
    walk_interactive_gate('test.md',        RUN_BUDGETS['code.md'])
    walk_interactive_gate('demo-review.md', RUN_BUDGETS['test.md'])
    walk_demo_review_gate
    redirect_at_demo_review
    assert_redirect_routed_back_to_code
  end

  private

  def configure_synthup
    @browser.wait_visible('setup-global', timeout: 10)
    @browser.fill('cfg-tenant',  ENV.fetch('SYNTHUP_TENANT'))
    @browser.fill('cfg-api_key', ENV.fetch('SYNTHUP_API_KEY'))
    @browser.click_text('Save')
    # The UI hides #setup-global once Synthup is configured (ui.html:333).
    @browser.wait_hidden('setup-global', timeout: 10)
  end

  def add_project
    @browser.wait_visible('projects', timeout: 10)
    @browser.fill('proj-url', "https://github.com/#{@repo}")
    @browser.click_text('Add project')
    # The active project marker is the user-visible signal the project was
    # added and is the orchestrator's target (ui.html:449-450).
    @browser.wait_until(timeout: 15, hint: 'project active marker') do
      list_text = @browser.text('projects-list') || ''
      list_text.include?(@repo) && list_text.include?('ACTIVE')
    end
  end

  # The first dispatch (issue-triage.md) bypasses the interactive gate by
  # design (run.rb:151-158). We assert it ran by watching #current-task-body
  # and then the history list.
  def wait_for_triage
    @browser.wait_text_in(
      'current-task-body',
      substring: 'issue-triage.md',
      timeout:   RUN_BUDGETS['issue-triage.md']
    )
    # When the task completes it leaves #current-task-body and lands in history.
    @browser.wait_text_in(
      'history-list',
      substring: 'issue-triage',
      timeout:   RUN_BUDGETS['issue-triage.md']
    )
  end

  def walk_interactive_gate(task, budget)
    @browser.wait_visible('next-action', timeout: budget)
    @browser.wait_text_in(
      'na-summary',
      substring: "run-task → #{task}",
      timeout:   10
    )
    @browser.click_text('Continue')
    @browser.wait_text_in(
      'current-task-body',
      substring: task,
      timeout:   60
    )
    # Opportunistically capture the PR URL whenever the running task surfaces
    # one (ui.html:363-370). Lets teardown clean up the PR even if the test
    # fails before the demo-review step.
    capture_pr_url_if_visible
  end

  def capture_pr_url_if_visible
    return if @pr_number
    href = @browser.attr('#current-task-body a[href*="/pull/"]', 'href')
    return unless href
    @pr_number = href[%r{/pull/(\d+)}, 1]&.to_i
  end

  # The interactive gate fires before wait-approval too (run.rb:243-248).
  # Walk it, then verify the demo-review section renders.
  def walk_demo_review_gate
    @browser.wait_visible('next-action', timeout: RUN_BUDGETS['demo-review.md'])
    @browser.wait_text_in(
      'na-summary',
      substring: 'wait-approval → demo review',
      timeout:   WAIT_APPROVAL_BUDGET
    )
    @browser.click_text('Continue')
    @browser.wait_visible('demo-review', timeout: 60)
  end

  def redirect_at_demo_review
    # The PR URL is rendered as an anchor in #dr-summary (ui.html:403-407).
    # Reading it from the DOM is exactly how a real user finds it.
    pr_url = @browser.attr('#dr-summary a', 'href')
    refute_nil pr_url, 'demo-review panel did not surface a PR URL'
    assert_match %r{github\.com/[^/]+/[^/]+/pull/\d+}, pr_url,
                 "PR URL in demo-review looks malformed: #{pr_url}"
    @pr_number = pr_url[%r{/pull/(\d+)}, 1].to_i

    @browser.fill('dr-feedback', 'e2e-test-cancel')
    @browser.click_text('Send Redirect')
    @browser.wait_hidden('demo-review', timeout: 30)
  end

  # Redirect from demo-review must route back to code.md per the router.
  # Asserting this proves the redirect was processed; we deliberately do NOT
  # click Continue afterward — that would burn another full code session.
  def assert_redirect_routed_back_to_code
    @browser.wait_visible('next-action', timeout: 30)
    @browser.wait_text_in(
      'na-summary',
      substring: 'run-task → code.md',
      timeout:   10
    )
  end
end
