# frozen_string_literal: true
#
# Unit tests for the Issue model and Issues module.

require 'minitest/autorun'

require_relative 'db_helper'
require_relative '../orchestrator/issues'
require_relative '../orchestrator/projects'

class TestIssueModel < Minitest::Test
  include DBHelper

  def setup
    setup_in_memory_db
  end

  def teardown
    teardown_in_memory_db
  end

  def test_table_exists
    assert Issue.table_exists?
  end

  def test_uuid_is_autogenerated
    i = Issue.create!(external_id: 'ENG-1')
    assert i.id
    assert_match(/\A[0-9a-f-]{36}\z/, i.id)
  end

  def test_source_defaults_to_linear
    i = Issue.create!(external_id: 'ENG-2')
    assert_equal 'linear', i.source
  end

  def test_unique_source_external_id
    Issue.create!(external_id: 'ENG-3')
    assert_raises(ActiveRecord::RecordNotUnique) do
      Issue.create!(external_id: 'ENG-3')
    end
  end

  def test_same_external_id_different_source_allowed
    Issue.create!(source: 'linear', external_id: 'X-1')
    Issue.create!(source: 'github', external_id: 'X-1')
    assert_equal 2, Issue.where(external_id: 'X-1').count
  end

  def test_project_link_optional
    i = Issue.create!(external_id: 'ENG-4')
    assert_nil i.project_id
  end

  def test_deleting_project_nullifies_project_id
    p = Projects.create(project_url: 'https://github.com/foo/bar')
    i = Issue.create!(external_id: 'ENG-5', project_id: p.id)
    Projects.delete(p.id)
    i.reload
    assert_nil i.project_id
  end
end

class TestIssuesUpsert < Minitest::Test
  include DBHelper

  def setup
    setup_in_memory_db
  end

  def teardown
    teardown_in_memory_db
  end

  def test_empty_external_id_returns_nil
    assert_nil Issues.upsert(external_id: '')
    assert_nil Issues.upsert(external_id: nil)
    assert_equal 0, Issue.count
  end

  def test_creates_and_then_updates_same_row
    a = Issues.upsert(external_id: 'ENG-10', cache: { title: 'first' })
    b = Issues.upsert(external_id: 'ENG-10', cache: { title: 'second' })
    assert_equal a.id, b.id
    assert_equal 'second', b.title
    assert_equal 1, Issue.count
  end

  def test_cache_assignment_sets_last_synced_at
    before = Time.now.utc - 1
    row = Issues.upsert(external_id: 'ENG-11', cache: { title: 't', status: 'In Progress', priority: 2, url: 'https://x' })
    assert_equal 't', row.title
    assert_equal 'In Progress', row.status
    assert_equal 2, row.priority
    assert_equal 'https://x', row.url
    assert row.last_synced_at >= before
  end

  def test_partial_cache_preserves_unrelated_fields
    Issues.upsert(external_id: 'ENG-12', cache: { title: 'orig', status: 'Todo' })
    Issues.upsert(external_id: 'ENG-12', cache: { status: 'Doing' })
    row = Issue.find_by!(external_id: 'ENG-12')
    assert_equal 'orig', row.title
    assert_equal 'Doing', row.status
  end

  def test_attempt_delta_accumulates
    Issues.upsert(external_id: 'ENG-13', ops: { attempt_delta: 1 })
    Issues.upsert(external_id: 'ENG-13', ops: { attempt_delta: 1 })
    assert_equal 2, Issue.find_by!(external_id: 'ENG-13').attempts
  end

  def test_project_id_assigned_only_once
    p1 = Projects.create(project_url: 'https://github.com/foo/bar')
    p2 = Projects.create(project_url: 'https://github.com/baz/qux')
    Issues.upsert(external_id: 'ENG-14', project_id: p1.id)
    Issues.upsert(external_id: 'ENG-14', project_id: p2.id)
    assert_equal p1.id, Issue.find_by!(external_id: 'ENG-14').project_id
  end

  def test_accepts_string_keys
    row = Issues.upsert(external_id: 'ENG-15', cache: { 'title' => 'sk' }, ops: { 'lifecycle_stage' => 'coding' })
    assert_equal 'sk', row.title
    assert_equal 'coding', row.lifecycle_stage
  end
end

class TestIssuesRecordEvent < Minitest::Test
  include DBHelper

  def setup
    setup_in_memory_db
    @project = Projects.create(project_url: 'https://github.com/foo/bar')
  end

  def teardown
    teardown_in_memory_db
  end

  def test_triage_report_with_hash_next_issue
    report = {
      'type' => 'triage-report',
      'next_issue' => { 'id' => 'ENG-100', 'title' => 'Fix bug', 'status' => 'Todo', 'priority' => 2, 'url' => 'https://linear.app/eng-100' },
      'next_task' => 'code'
    }
    row = Issues.record_event(@project.id, report)
    assert_equal 'ENG-100', row.external_id
    assert_equal 'Fix bug', row.title
    assert_equal 'Todo', row.status
    assert_equal 2, row.priority
    assert_equal 'triaged', row.lifecycle_stage
    assert_equal @project.id, row.project_id
  end

  def test_triage_report_with_string_next_issue
    report = { 'type' => 'triage-report', 'next_issue' => 'ENG-101', 'next_task' => 'code' }
    row = Issues.record_event(@project.id, report)
    assert_equal 'ENG-101', row.external_id
    assert_equal 'triaged', row.lifecycle_stage
  end

  def test_task_complete_advances_to_testing
    report = { 'type' => 'task-complete', 'issue_id' => 'ENG-102', 'pr_url' => 'https://github.com/foo/bar/pull/1' }
    current_task = { 'task' => 'code.md', 'session_id' => 'sess-1' }
    row = Issues.record_event(@project.id, report, current_task: current_task)
    assert_equal 'testing', row.lifecycle_stage
    assert_equal 'https://github.com/foo/bar/pull/1', row.last_pr_url
    assert_equal 'code.md', row.last_task
    assert_equal 'sess-1', row.last_session_id
    refute_nil row.last_event_at
  end

  def test_test_report_pass_moves_to_reviewing
    report = { 'type' => 'test-report', 'issue_id' => 'ENG-103', 'outcome' => 'pass' }
    row = Issues.record_event(@project.id, report)
    assert_equal 'reviewing', row.lifecycle_stage
  end

  def test_test_report_fail_returns_to_coding
    report = { 'type' => 'test-report', 'issue_id' => 'ENG-104', 'outcome' => 'fail' }
    row = Issues.record_event(@project.id, report)
    assert_equal 'coding', row.lifecycle_stage
  end

  def test_demo_review_approved_marks_done
    report = { 'type' => 'demo-review-report', 'issue_id' => 'ENG-105', 'outcome' => 'approved' }
    row = Issues.record_event(@project.id, report)
    assert_equal 'done', row.lifecycle_stage
  end

  def test_demo_review_redirect_returns_to_coding
    report = { 'type' => 'demo-review-report', 'issue_id' => 'ENG-106', 'outcome' => 'redirect' }
    row = Issues.record_event(@project.id, report)
    assert_equal 'coding', row.lifecycle_stage
  end

  def test_report_without_issue_returns_nil
    assert_nil Issues.record_event(@project.id, { 'type' => 'task-failed', 'details' => 'oops' })
    assert_equal 0, Issue.count
  end

  def test_non_hash_report_returns_nil
    assert_nil Issues.record_event(@project.id, nil)
    assert_nil Issues.record_event(@project.id, 'not a hash')
  end
end
