# frozen_string_literal: true
#
# Unit tests for the Issue model and Issues module.

require 'minitest/autorun'

require_relative 'db_helper'
require_relative '../orchestrator/issues'

class TestIssueModel < Minitest::Test
  include DBHelper

  def setup
    setup_in_memory_db
  end

  def teardown
    teardown_in_memory_db
  end

  def test_table_exists
    assert Issue.table_exists?
  end

  def test_uuid_is_autogenerated
    i = Issue.create!(lifecycle_stage: 'coding')
    assert i.id
    assert_match(/\A[0-9a-f-]{36}\z/, i.id)
  end

  def test_new_columns_present
    i = Issue.create!(input_text: 'Fix the bug', repo_url: 'https://github.com/owner/repo',
                      lifecycle_stage: 'coding')
    assert_equal 'Fix the bug', i.input_text
    assert_equal 'https://github.com/owner/repo', i.repo_url
    assert_nil i.history
  end

  def test_external_id_is_nullable
    i = Issue.create!(lifecycle_stage: 'coding')
    assert_nil i.external_id
  end

  def test_history_is_json_array
    i = Issue.create!(lifecycle_stage: 'coding')
    i.update!(history: [{ 'task' => 'code.md' }])
    i.reload
    assert_equal [{ 'task' => 'code.md' }], i.history
  end
end

class TestIssuesSetCurrentTask < Minitest::Test
  include DBHelper

  def setup
    setup_in_memory_db
    @issue = Issue.create!(input_text: 'Fix it', repo_url: 'https://github.com/a/b',
                           lifecycle_stage: 'coding')
  end

  def teardown
    teardown_in_memory_db
  end

  def test_sets_current_task
    Issues.set_current_task(@issue.id, { 'task' => 'code.md', 'started_at' => '2026-01-01T00:00:00Z' })
    @issue.reload
    assert_equal 'code.md', @issue.current_task['task']
  end

  def test_clears_escalation_when_setting_task
    Issues.set_escalation(@issue.id, { 'reason' => 'task-failed' })
    Issues.set_current_task(@issue.id, { 'task' => 'code.md' })
    @issue.reload
    assert_nil @issue.escalation
  end

  def test_clear_current_task
    Issues.set_current_task(@issue.id, { 'task' => 'code.md' })
    Issues.clear_current_task(@issue.id)
    @issue.reload
    assert_nil @issue.current_task
  end

  def test_returns_nil_for_unknown_id
    assert_nil Issues.set_current_task('nonexistent-uuid', { 'task' => 'code.md' })
    assert_nil Issues.clear_current_task('nonexistent-uuid')
  end
end

class TestIssuesEscalation < Minitest::Test
  include DBHelper

  def setup
    setup_in_memory_db
    @issue = Issue.create!(input_text: 'Fix it', repo_url: 'https://github.com/a/b',
                           lifecycle_stage: 'coding')
  end

  def teardown
    teardown_in_memory_db
  end

  def test_sets_escalation
    Issues.set_escalation(@issue.id, { 'reason' => 'task-failed', 'details' => 'oops' })
    @issue.reload
    assert_equal 'task-failed', @issue.escalation['reason']
    assert_equal 'oops', @issue.escalation['details']
  end

  def test_clears_escalation
    Issues.set_escalation(@issue.id, { 'reason' => 'task-failed' })
    Issues.clear_escalation(@issue.id)
    @issue.reload
    assert_nil @issue.escalation
  end

  def test_returns_nil_for_unknown_id
    assert_nil Issues.set_escalation('nonexistent-uuid', { 'reason' => 'task-failed' })
    assert_nil Issues.clear_escalation('nonexistent-uuid')
  end
end

class TestIssuesAppendHistory < Minitest::Test
  include DBHelper

  def setup
    setup_in_memory_db
    @issue = Issue.create!(input_text: 'Fix it', repo_url: 'https://github.com/a/b',
                           lifecycle_stage: 'coding')
  end

  def teardown
    teardown_in_memory_db
  end

  def test_appends_entry
    Issues.append_history(@issue.id, { 'task' => 'code.md', 'duration_s' => 60 })
    @issue.reload
    assert_equal 1, @issue.history.length
    assert_equal 'code.md', @issue.history.first['task']
  end

  def test_appends_multiple_entries_in_order
    Issues.append_history(@issue.id, { 'task' => 'code.md' })
    Issues.append_history(@issue.id, { 'task' => 'test.md' })
    @issue.reload
    assert_equal 2, @issue.history.length
    assert_equal 'code.md', @issue.history[0]['task']
    assert_equal 'test.md', @issue.history[1]['task']
  end

  def test_returns_nil_for_unknown_id
    assert_nil Issues.append_history('nonexistent-uuid', { 'task' => 'code.md' })
  end
end
